@baseUrl = https://medacare-be.onrender.com/api/v1
@patient_token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NDk1MDQ2LCJpYXQiOjE3NDU0OTQxNDYsImp0aSI6ImRjNGY5M2U3NTc5MDQwZGViNWE1OGE4ZmFjM2YzYTcyIiwidXNlcl9pZCI6Mn0.C1ja2HFiDuqZk8m9o5DCiHh9owXQmGIHFYhjOAJzdvI
@admin_token = Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjFAZ21haWwuY29tIiwiaWF0IjoxNzQ3MjE0NDQ0LCJleHAiOjE3NTUxMDM4NDR9.Jmfn1PV0KGtz5koMz5lQoaH5JkQzU_JS1Vu0sxFq97k
@institution_token = Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtaW5kYWh1bnhwc0BnbWFpbC5jb20iLCJpYXQiOjE3NDcyMjIyNTMsImV4cCI6MTc1NTExMTY1M30.KgkqOggWNuh5YDRzMoXXC8jtrCjOPuPGK_TpMm7dBzM
@physician_token = Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJldGhpb3Rlc3QxMEBnbWFpbC5jb20iLCJpYXQiOjE3NDcyMTMxMDcsImV4cCI6MTc1NTEwMjUwN30.ikafngznRDOLuK7p7e4Z-9pwVmh8nDMIfIgUsGXkDFA
@patients_token = Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwYXRpZW50MkBnbWFpbC5jb20iLCJpYXQiOjE3NDc2NzcxNzEsImV4cCI6MTc1NTU2NjU3MX0.UUIkZlNNIexpGt5Qazqu-jSeW5k9kSLpFUcUnyi4XSI


@profilePhoto=/home/mindahun/Pictures/bike/bike1.png
@file=/home/mindahun/Documents/Game1-code-2025.pdf


###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "mindahunthebest@gmail.com",
  "password": "qwe@QWE123"
}

###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin1@gmail.com",
  "password": "12345678"
}

###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "patient2@gmail.com",
  "password": "12345678"
}

###
POST {{baseUrl}}/physicians/work-hour
Content-Type: application/json
Authorization: {{physician_token}}

{
  "date": "2025-10-08",
  "startTime": "02:30:00",
  "endTime": "10:30:00"
}

###
GET {{baseUrl}}/users/current
Content-Type: application/json
Authorization: {{institution_token}}

###
GET {{baseUrl}}/physicians/work-hour
Content-Type: application/json
Authorization: {{physician_token}}

###
DELETE {{baseUrl}}/physicians/work-hour/2
Content-Type: application/json
Authorization: {{physician_token}}

###
GET {{baseUrl}}/patients
Content-Type: application/json
Authorization: {{admin_token}}

###
GET {{baseUrl}}/physicians
Content-Type: application/json
Authorization: {{admin_token}}

###
GET {{baseUrl}}/institutions
Content-Type: application/json
Authorization: {{admin_token}}

###
GET {{baseUrl}}/physicians
Content-Type: application/json
Authorization: {{institution_token}}

###
GET {{baseUrl}}/institutions
Content-Type: application/json
Authorization: {{institution_token}}

###
GET {{baseUrl}}/institutions/physicians  
Content-Type: application/json
Authorization: {{institution_token}}


###
GET {{baseUrl}}/physicians/1/available/dates
Content-Type: application/json
Authorization: {{physician_token}}



###   no resource found
GET {{baseUrl}}/workingHoursWindows/1
Content-Type: application/json
Authorization: {{physician_token}}



###   no resource found
GET {{baseUrl}}/physicians/appointments
Content-Type: application/json
Authorization: {{physician_token}}


###   no resource found
GET {{baseUrl}}/recommendations/physician
Content-Type: application/json
Authorization: {{patients_token}}

###   no resource found
GET {{baseUrl}}/recommendations/institution
Content-Type: application/json
Authorization: {{patients_token}}


###   no resource found
GET {{baseUrl}}/physicians/6/available/dates
Content-Type: application/json
Authorization: {{patients_token}}


###   no resource found
GET {{baseUrl}}/physicians/6/available-slots/2025-05-22/30
Content-Type: application/json
Authorization: {{patients_token}}




###   no resource found
POST {{baseUrl}}/physicians/book/slot/26
Content-Type: application/json
Authorization: {{patients_token}}


###   no resource found
POST {{baseUrl}}/physicians/booking/finalization/26
Content-Type: application/json
Authorization: {{patients_token}}

###
POST {{baseUrl}}/assistance/consultation
Content-Type: text/plain
Authorization: {{physician_token}}

How can I improve my sleep quality?



###   no resource found
GET {{baseUrl}}/reports/physician/dashboard
Content-Type: application/json
Authorization: {{physician_token}}

###   no resource found
GET {{baseUrl}}/reports/admin/dashboard
Content-Type: application/json
Authorization: {{admin_token}}

###   no resource found
GET {{baseUrl}}/reports/institution/dashboard
Content-Type: application/json
Authorization: {{institution_token}}


###
GET {{baseUrl}}/institutions/physicians
Authorization: {{institution_token}}
Content-Type: application/json


###
POST {{baseUrl}}/institutions/physicians
Authorization: {{institution_token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="specialization"

Cardiology
--boundary
Content-Disposition: form-data; name="licenseNumber"

ABC123456
--boundary
Content-Disposition: form-data; name="education"

MD, Cardiology
--boundary
Content-Disposition: form-data; name="gender"

Male
--boundary
Content-Disposition: form-data; name="dateOfBirth"

1980-05-13
--boundary
Content-Disposition: form-data; name="experience"

15
--boundary
Content-Disposition: form-data; name="languagesSpoken"

English, Amharic
--boundary
Content-Disposition: form-data; name="email"

doctormy@example.com
--boundary
Content-Disposition: form-data; name="firstName"

John
--boundary
Content-Disposition: form-data; name="lastName"

Doe
--boundary
Content-Disposition: form-data; name="phoneNumber"

+251912345678
--boundary
Content-Disposition: form-data; name="profilePhoto"; filename="photo.jpg"
Content-Type: image/jpeg

{{profilePhoto}}
--boundary
Content-Disposition: form-data; name="nationalId"; filename="national_id.pdf"
Content-Type: application/pdf

{{file}}
--boundary
Content-Disposition: form-data; name="resume"; filename="resume.pdf"
Content-Type: application/pdf

{{file}}
--boundary
Content-Disposition: form-data; name="medicalLicense"; filename="license.pdf"
Content-Type: application/pdf

{{file}}
--boundary
Content-Disposition: form-data; name="specializationDoc"; filename="specialization.pdf"
Content-Type: application/pdf

{{file}}
--boundary
Content-Disposition: form-data; name="degreeCertificate"; filename="degree.pdf"
Content-Type: application/pdf

{{file}}
--boundary--


